export enum EScreen {
    DASHBOARD = "DASHBOARD",
    ACCOUNT_MANAGEMENT = "ACCOUNT_MANAGEMENT",
    ACADEMIC_MANAGEMENT = "ACADEMIC_MANAGEMENT",
    EXAM_MANAGEMENT = "EXAM_MANAGEMENT",
    REPORT_MANAGEMENT = "REPORT_MANAGEMENT",
    PORTAL_MANAGEMENT = "PORTAL_MANAGEMENT",
    COMMUNICATION_MANAGEMENT = "COMMUNICATION_MANAGEMENT",
    SETTINGS = "SETTINGS",
    ORGANIZATION_MANAGEMENT = "ORGANIZATION_MANAGEMENT",
}
